/**
 * Shared curated icon library (Lucide outline, 24×24, 2px stroke).
 *
 * GENERATED by scripts/build-icons.js from scripts/icons.manifest.json — do not
 * edit by hand. Add/remove icons in the manifest, then run `npm run build:icons`.
 * Keep in sync with inc/Blocks/Icons.php (the generator writes both).
 *
 * Icons are referenced by slug and the SVG is resolved at render time, so the
 * set can grow without saved-markup migrations. No width/height on the shell —
 * size is controlled by the consuming block's CSS.
 */

import { __ } from '@wordpress/i18n';

const Svg = ( { children } ) => (
	<svg
		viewBox="0 0 24 24"
		fill="none"
		stroke="currentColor"
		strokeWidth="2"
		strokeLinecap="round"
		strokeLinejoin="round"
		aria-hidden="true"
	>
		{ children }
	</svg>
);

export const ICON_LIBRARY = {
	'arrow-right': (
		<Svg>
			<path d="M5 12h14" /> <path d="m12 5 7 7-7 7" />
		</Svg>
	),
	'arrow-left': (
		<Svg>
			<path d="m12 19-7-7 7-7" /> <path d="M19 12H5" />
		</Svg>
	),
	'arrow-up': (
		<Svg>
			<path d="m5 12 7-7 7 7" /> <path d="M12 19V5" />
		</Svg>
	),
	'arrow-down': (
		<Svg>
			<path d="M12 5v14" /> <path d="m19 12-7 7-7-7" />
		</Svg>
	),
	'arrow-up-right': (
		<Svg>
			<path d="M7 7h10v10" /> <path d="M7 17 17 7" />
		</Svg>
	),
	'chevron-right': (
		<Svg>
			<path d="m9 18 6-6-6-6" />
		</Svg>
	),
	'chevron-left': (
		<Svg>
			<path d="m15 18-6-6 6-6" />
		</Svg>
	),
	'chevron-up': (
		<Svg>
			<path d="m18 15-6-6-6 6" />
		</Svg>
	),
	'chevron-down': (
		<Svg>
			<path d="m6 9 6 6 6-6" />
		</Svg>
	),
	'chevrons-right': (
		<Svg>
			<path d="m6 17 5-5-5-5" /> <path d="m13 17 5-5-5-5" />
		</Svg>
	),
	'external-link': (
		<Svg>
			<path d="M15 3h6v6" /> <path d="M10 14 21 3" />{ ' ' }
			<path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
		</Svg>
	),
	move: (
		<Svg>
			<path d="M12 2v20" /> <path d="m15 19-3 3-3-3" />{ ' ' }
			<path d="m19 9 3 3-3 3" /> <path d="M2 12h20" />{ ' ' }
			<path d="m5 9-3 3 3 3" /> <path d="m9 5 3-3 3 3" />
		</Svg>
	),
	'refresh-cw': (
		<Svg>
			<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />{ ' ' }
			<path d="M21 3v5h-5" />{ ' ' }
			<path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />{ ' ' }
			<path d="M8 16H3v5" />
		</Svg>
	),
	'more-horizontal': (
		<Svg>
			<circle cx="12" cy="12" r="1" /> <circle cx="19" cy="12" r="1" />{ ' ' }
			<circle cx="5" cy="12" r="1" />
		</Svg>
	),
	check: (
		<Svg>
			<path d="M20 6 9 17l-5-5" />
		</Svg>
	),
	'check-circle': (
		<Svg>
			<path d="M21.801 10A10 10 0 1 1 17 3.335" />{ ' ' }
			<path d="m9 11 3 3L22 4" />
		</Svg>
	),
	x: (
		<Svg>
			<path d="M18 6 6 18" /> <path d="m6 6 12 12" />
		</Svg>
	),
	'circle-x': (
		<Svg>
			<circle cx="12" cy="12" r="10" /> <path d="m15 9-6 6" />{ ' ' }
			<path d="m9 9 6 6" />
		</Svg>
	),
	plus: (
		<Svg>
			<path d="M5 12h14" /> <path d="M12 5v14" />
		</Svg>
	),
	minus: (
		<Svg>
			<path d="M5 12h14" />
		</Svg>
	),
	'circle-plus': (
		<Svg>
			<circle cx="12" cy="12" r="10" /> <path d="M8 12h8" />{ ' ' }
			<path d="M12 8v8" />
		</Svg>
	),
	menu: (
		<Svg>
			<path d="M4 5h16" /> <path d="M4 12h16" /> <path d="M4 19h16" />
		</Svg>
	),
	list: (
		<Svg>
			<path d="M3 5h.01" /> <path d="M3 12h.01" /> <path d="M3 19h.01" />{ ' ' }
			<path d="M8 5h13" /> <path d="M8 12h13" /> <path d="M8 19h13" />
		</Svg>
	),
	'layout-grid': (
		<Svg>
			<rect width="7" height="7" x="3" y="3" rx="1" />{ ' ' }
			<rect width="7" height="7" x="14" y="3" rx="1" />{ ' ' }
			<rect width="7" height="7" x="14" y="14" rx="1" />{ ' ' }
			<rect width="7" height="7" x="3" y="14" rx="1" />
		</Svg>
	),
	search: (
		<Svg>
			<path d="m21 21-4.34-4.34" /> <circle cx="11" cy="11" r="8" />
		</Svg>
	),
	filter: (
		<Svg>
			<path d="M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z" />
		</Svg>
	),
	'sliders-horizontal': (
		<Svg>
			<path d="M10 5H3" /> <path d="M12 19H3" /> <path d="M14 3v4" />{ ' ' }
			<path d="M16 17v4" /> <path d="M21 12h-9" /> <path d="M21 19h-5" />{ ' ' }
			<path d="M21 5h-7" /> <path d="M8 10v4" /> <path d="M8 12H3" />
		</Svg>
	),
	settings: (
		<Svg>
			<path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915" />{ ' ' }
			<circle cx="12" cy="12" r="3" />
		</Svg>
	),
	info: (
		<Svg>
			<circle cx="12" cy="12" r="10" /> <path d="M12 16v-4" />{ ' ' }
			<path d="M12 8h.01" />
		</Svg>
	),
	'circle-help': (
		<Svg>
			<circle cx="12" cy="12" r="10" />{ ' ' }
			<path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />{ ' ' }
			<path d="M12 17h.01" />
		</Svg>
	),
	'alert-triangle': (
		<Svg>
			<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" />{ ' ' }
			<path d="M12 9v4" /> <path d="M12 17h.01" />
		</Svg>
	),
	ban: (
		<Svg>
			<circle cx="12" cy="12" r="10" />{ ' ' }
			<path d="M4.929 4.929 19.07 19.071" />
		</Svg>
	),
	eye: (
		<Svg>
			<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" />{ ' ' }
			<circle cx="12" cy="12" r="3" />
		</Svg>
	),
	'eye-off': (
		<Svg>
			<path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49" />{ ' ' }
			<path d="M14.084 14.158a3 3 0 0 1-4.242-4.242" />{ ' ' }
			<path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143" />{ ' ' }
			<path d="m2 2 20 20" />
		</Svg>
	),
	lock: (
		<Svg>
			<rect width="18" height="11" x="3" y="11" rx="2" ry="2" />{ ' ' }
			<path d="M7 11V7a5 5 0 0 1 10 0v4" />
		</Svg>
	),
	shield: (
		<Svg>
			<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
		</Svg>
	),
	bookmark: (
		<Svg>
			<path d="M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z" />
		</Svg>
	),
	download: (
		<Svg>
			<path d="M12 15V3" />{ ' ' }
			<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />{ ' ' }
			<path d="m7 10 5 5 5-5" />
		</Svg>
	),
	upload: (
		<Svg>
			<path d="M12 3v12" /> <path d="m17 8-5-5-5 5" />{ ' ' }
			<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
		</Svg>
	),
	power: (
		<Svg>
			<path d="M12 2v10" /> <path d="M18.4 6.6a9 9 0 1 1-12.77.04" />
		</Svg>
	),
	'log-in': (
		<Svg>
			<path d="m10 17 5-5-5-5" /> <path d="M15 12H3" />{ ' ' }
			<path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
		</Svg>
	),
	'log-out': (
		<Svg>
			<path d="m16 17 5-5-5-5" /> <path d="M21 12H9" />{ ' ' }
			<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
		</Svg>
	),
	zap: (
		<Svg>
			<path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z" />
		</Svg>
	),
	pencil: (
		<Svg>
			<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />{ ' ' }
			<path d="m15 5 4 4" />
		</Svg>
	),
	'trash-2': (
		<Svg>
			<path d="M10 11v6" /> <path d="M14 11v6" />{ ' ' }
			<path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" />{ ' ' }
			<path d="M3 6h18" />{ ' ' }
			<path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
		</Svg>
	),
	copy: (
		<Svg>
			<rect width="14" height="14" x="8" y="8" rx="2" ry="2" />{ ' ' }
			<path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
		</Svg>
	),
	clipboard: (
		<Svg>
			<rect width="8" height="4" x="8" y="2" rx="1" ry="1" />{ ' ' }
			<path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
		</Svg>
	),
	scissors: (
		<Svg>
			<circle cx="6" cy="6" r="3" /> <path d="M8.12 8.12 12 12" />{ ' ' }
			<path d="M20 4 8.12 15.88" /> <circle cx="6" cy="18" r="3" />{ ' ' }
			<path d="M14.8 14.8 20 20" />
		</Svg>
	),
	file: (
		<Svg>
			<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" />{ ' ' }
			<path d="M14 2v5a1 1 0 0 0 1 1h5" />
		</Svg>
	),
	'file-text': (
		<Svg>
			<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" />{ ' ' }
			<path d="M14 2v5a1 1 0 0 0 1 1h5" /> <path d="M10 9H8" />{ ' ' }
			<path d="M16 13H8" /> <path d="M16 17H8" />
		</Svg>
	),
	folder: (
		<Svg>
			<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
		</Svg>
	),
	'folder-open': (
		<Svg>
			<path d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2" />
		</Svg>
	),
	paperclip: (
		<Svg>
			<path d="m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551" />
		</Svg>
	),
	printer: (
		<Svg>
			<path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />{ ' ' }
			<path d="M6 9V3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6" />{ ' ' }
			<rect x="6" y="14" width="12" height="8" rx="1" />
		</Svg>
	),
	archive: (
		<Svg>
			<rect width="20" height="5" x="2" y="3" rx="1" />{ ' ' }
			<path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8" />{ ' ' }
			<path d="M10 12h4" />
		</Svg>
	),
	cart: (
		<Svg>
			<circle cx="8" cy="21" r="1" /> <circle cx="19" cy="21" r="1" />{ ' ' }
			<path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
		</Svg>
	),
	'shopping-bag': (
		<Svg>
			<path d="M16 10a4 4 0 0 1-8 0" /> <path d="M3.103 6.034h17.794" />{ ' ' }
			<path d="M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z" />
		</Svg>
	),
	store: (
		<Svg>
			<path d="M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5" />{ ' ' }
			<path d="M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244" />{ ' ' }
			<path d="M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05" />
		</Svg>
	),
	tag: (
		<Svg>
			<path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z" />{ ' ' }
			<circle cx="7.5" cy="7.5" r=".5" fill="currentColor" />
		</Svg>
	),
	gift: (
		<Svg>
			<path d="M12 7v14" />{ ' ' }
			<path d="M20 11v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8" />{ ' ' }
			<path d="M7.5 7a1 1 0 0 1 0-5A4.8 8 0 0 1 12 7a4.8 8 0 0 1 4.5-5 1 1 0 0 1 0 5" />{ ' ' }
			<rect x="3" y="7" width="18" height="4" rx="1" />
		</Svg>
	),
	'credit-card': (
		<Svg>
			<rect width="20" height="14" x="2" y="5" rx="2" />{ ' ' }
			<line x1="2" x2="22" y1="10" y2="10" />
		</Svg>
	),
	wallet: (
		<Svg>
			<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />{ ' ' }
			<path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
		</Svg>
	),
	banknote: (
		<Svg>
			<rect width="20" height="12" x="2" y="6" rx="2" />{ ' ' }
			<circle cx="12" cy="12" r="2" /> <path d="M6 12h.01M18 12h.01" />
		</Svg>
	),
	'dollar-sign': (
		<Svg>
			<line x1="12" x2="12" y1="2" y2="22" />{ ' ' }
			<path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
		</Svg>
	),
	percent: (
		<Svg>
			<line x1="19" x2="5" y1="5" y2="19" />{ ' ' }
			<circle cx="6.5" cy="6.5" r="2.5" />{ ' ' }
			<circle cx="17.5" cy="17.5" r="2.5" />
		</Svg>
	),
	receipt: (
		<Svg>
			<path d="M12 17V7" />{ ' ' }
			<path d="M16 8h-6a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H8" />{ ' ' }
			<path d="M4 3a1 1 0 0 1 1-1 1.3 1.3 0 0 1 .7.2l.933.6a1.3 1.3 0 0 0 1.4 0l.934-.6a1.3 1.3 0 0 1 1.4 0l.933.6a1.3 1.3 0 0 0 1.4 0l.933-.6a1.3 1.3 0 0 1 1.4 0l.934.6a1.3 1.3 0 0 0 1.4 0l.933-.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1 1.3 1.3 0 0 1-.7-.2l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.934.6a1.3 1.3 0 0 1-1.4 0l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-1.4 0l-.934-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-.7.2 1 1 0 0 1-1-1z" />
		</Svg>
	),
	package: (
		<Svg>
			<path d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z" />{ ' ' }
			<path d="M12 22V12" /> <polyline points="3.29 7 12 12 20.71 7" />{ ' ' }
			<path d="m7.5 4.27 9 5.15" />
		</Svg>
	),
	truck: (
		<Svg>
			<path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />{ ' ' }
			<path d="M15 18H9" />{ ' ' }
			<path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" />{ ' ' }
			<circle cx="17" cy="18" r="2" /> <circle cx="7" cy="18" r="2" />
		</Svg>
	),
	ticket: (
		<Svg>
			<path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" />{ ' ' }
			<path d="M13 5v2" /> <path d="M13 17v2" /> <path d="M13 11v2" />
		</Svg>
	),
	award: (
		<Svg>
			<path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526" />{ ' ' }
			<circle cx="12" cy="8" r="6" />
		</Svg>
	),
	'trending-up': (
		<Svg>
			<path d="M16 7h6v6" /> <path d="m22 7-8.5 8.5-5-5L2 17" />
		</Svg>
	),
	mail: (
		<Svg>
			<path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7" />{ ' ' }
			<rect x="2" y="4" width="20" height="16" rx="2" />
		</Svg>
	),
	'at-sign': (
		<Svg>
			<circle cx="12" cy="12" r="4" />{ ' ' }
			<path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8" />
		</Svg>
	),
	phone: (
		<Svg>
			<path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384" />
		</Svg>
	),
	send: (
		<Svg>
			<path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" />{ ' ' }
			<path d="m21.854 2.147-10.94 10.939" />
		</Svg>
	),
	'message-circle': (
		<Svg>
			<path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719" />
		</Svg>
	),
	'message-square': (
		<Svg>
			<path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z" />
		</Svg>
	),
	inbox: (
		<Svg>
			<polyline points="22 12 16 12 14 15 10 15 8 12 2 12" />{ ' ' }
			<path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z" />
		</Svg>
	),
	bell: (
		<Svg>
			<path d="M10.268 21a2 2 0 0 0 3.464 0" />{ ' ' }
			<path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" />
		</Svg>
	),
	megaphone: (
		<Svg>
			<path d="M11 6a13 13 0 0 0 8.4-2.8A1 1 0 0 1 21 4v12a1 1 0 0 1-1.6.8A13 13 0 0 0 11 14H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z" />{ ' ' }
			<path d="M6 14a12 12 0 0 0 2.4 7.2 2 2 0 0 0 3.2-2.4A8 8 0 0 1 10 14" />{ ' ' }
			<path d="M8 6v8" />
		</Svg>
	),
	globe: (
		<Svg>
			<circle cx="12" cy="12" r="10" />{ ' ' }
			<path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />{ ' ' }
			<path d="M2 12h20" />
		</Svg>
	),
	link: (
		<Svg>
			<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />{ ' ' }
			<path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
		</Svg>
	),
	share: (
		<Svg>
			<circle cx="18" cy="5" r="3" /> <circle cx="6" cy="12" r="3" />{ ' ' }
			<circle cx="18" cy="19" r="3" />{ ' ' }
			<line x1="8.59" x2="15.42" y1="13.51" y2="17.49" />{ ' ' }
			<line x1="15.41" x2="8.59" y1="6.51" y2="10.49" />
		</Svg>
	),
	rss: (
		<Svg>
			<path d="M4 11a9 9 0 0 1 9 9" /> <path d="M4 4a16 16 0 0 1 16 16" />{ ' ' }
			<circle cx="5" cy="19" r="1" />
		</Svg>
	),
	wifi: (
		<Svg>
			<path d="M12 20h.01" /> <path d="M2 8.82a15 15 0 0 1 20 0" />{ ' ' }
			<path d="M5 12.859a10 10 0 0 1 14 0" />{ ' ' }
			<path d="M8.5 16.429a5 5 0 0 1 7 0" />
		</Svg>
	),
	play: (
		<Svg>
			<path d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z" />
		</Svg>
	),
	pause: (
		<Svg>
			<rect x="14" y="3" width="5" height="18" rx="1" />{ ' ' }
			<rect x="5" y="3" width="5" height="18" rx="1" />
		</Svg>
	),
	'skip-forward': (
		<Svg>
			<path d="M21 4v16" />{ ' ' }
			<path d="M6.029 4.285A2 2 0 0 0 3 6v12a2 2 0 0 0 3.029 1.715l9.997-5.998a2 2 0 0 0 .003-3.432z" />
		</Svg>
	),
	'skip-back': (
		<Svg>
			<path d="M17.971 4.285A2 2 0 0 1 21 6v12a2 2 0 0 1-3.029 1.715l-9.997-5.998a2 2 0 0 1-.003-3.432z" />{ ' ' }
			<path d="M3 20V4" />
		</Svg>
	),
	image: (
		<Svg>
			<rect width="18" height="18" x="3" y="3" rx="2" ry="2" />{ ' ' }
			<circle cx="9" cy="9" r="2" />{ ' ' }
			<path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
		</Svg>
	),
	video: (
		<Svg>
			<path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />{ ' ' }
			<rect x="2" y="6" width="14" height="12" rx="2" />
		</Svg>
	),
	film: (
		<Svg>
			<rect width="18" height="18" x="3" y="3" rx="2" />{ ' ' }
			<path d="M7 3v18" /> <path d="M3 7.5h4" /> <path d="M3 12h18" />{ ' ' }
			<path d="M3 16.5h4" /> <path d="M17 3v18" /> <path d="M17 7.5h4" />{ ' ' }
			<path d="M17 16.5h4" />
		</Svg>
	),
	music: (
		<Svg>
			<path d="M9 18V5l12-2v13" /> <circle cx="6" cy="18" r="3" />{ ' ' }
			<circle cx="18" cy="16" r="3" />
		</Svg>
	),
	headphones: (
		<Svg>
			<path d="M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3" />
		</Svg>
	),
	mic: (
		<Svg>
			<path d="M12 19v3" /> <path d="M19 10v2a7 7 0 0 1-14 0v-2" />{ ' ' }
			<rect x="9" y="2" width="6" height="13" rx="3" />
		</Svg>
	),
	'volume-2': (
		<Svg>
			<path d="M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z" />{ ' ' }
			<path d="M16 9a5 5 0 0 1 0 6" />{ ' ' }
			<path d="M19.364 18.364a9 9 0 0 0 0-12.728" />
		</Svg>
	),
	camera: (
		<Svg>
			<path d="M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z" />{ ' ' }
			<circle cx="12" cy="13" r="3" />
		</Svg>
	),
	user: (
		<Svg>
			<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />{ ' ' }
			<circle cx="12" cy="7" r="4" />
		</Svg>
	),
	users: (
		<Svg>
			<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />{ ' ' }
			<path d="M16 3.128a4 4 0 0 1 0 7.744" />{ ' ' }
			<path d="M22 21v-2a4 4 0 0 0-3-3.87" />{ ' ' }
			<circle cx="9" cy="7" r="4" />
		</Svg>
	),
	'user-plus': (
		<Svg>
			<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />{ ' ' }
			<circle cx="9" cy="7" r="4" />{ ' ' }
			<line x1="19" x2="19" y1="8" y2="14" />{ ' ' }
			<line x1="22" x2="16" y1="11" y2="11" />
		</Svg>
	),
	smile: (
		<Svg>
			<circle cx="12" cy="12" r="10" />{ ' ' }
			<path d="M8 14s1.5 2 4 2 4-2 4-2" />{ ' ' }
			<line x1="9" x2="9.01" y1="9" y2="9" />{ ' ' }
			<line x1="15" x2="15.01" y1="9" y2="9" />
		</Svg>
	),
	heart: (
		<Svg>
			<path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5" />
		</Svg>
	),
	star: (
		<Svg>
			<path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z" />
		</Svg>
	),
	'thumbs-up': (
		<Svg>
			<path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z" />{ ' ' }
			<path d="M7 10v12" />
		</Svg>
	),
	'thumbs-down': (
		<Svg>
			<path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22a3.13 3.13 0 0 1-3-3.88Z" />{ ' ' }
			<path d="M17 14V2" />
		</Svg>
	),
	trophy: (
		<Svg>
			<path d="M10 14.66v1.626a2 2 0 0 1-.976 1.696A5 5 0 0 0 7 21.978" />{ ' ' }
			<path d="M14 14.66v1.626a2 2 0 0 0 .976 1.696A5 5 0 0 1 17 21.978" />{ ' ' }
			<path d="M18 9h1.5a1 1 0 0 0 0-5H18" /> <path d="M4 22h16" />{ ' ' }
			<path d="M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z" />{ ' ' }
			<path d="M6 9H4.5a1 1 0 0 1 0-5H6" />
		</Svg>
	),
	flag: (
		<Svg>
			<path d="M4 22V4a1 1 0 0 1 .4-.8A6 6 0 0 1 8 2c3 0 5 2 7.333 2q2 0 3.067-.8A1 1 0 0 1 20 4v10a1 1 0 0 1-.4.8A6 6 0 0 1 16 16c-3 0-5-2-8-2a6 6 0 0 0-4 1.528" />
		</Svg>
	),
	home: (
		<Svg>
			<path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8" />{ ' ' }
			<path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
		</Svg>
	),
	calendar: (
		<Svg>
			<path d="M8 2v4" /> <path d="M16 2v4" />{ ' ' }
			<rect width="18" height="18" x="3" y="4" rx="2" />{ ' ' }
			<path d="M3 10h18" />
		</Svg>
	),
	clock: (
		<Svg>
			<circle cx="12" cy="12" r="10" /> <path d="M12 6v6l4 2" />
		</Svg>
	),
	'map-pin': (
		<Svg>
			<path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0" />{ ' ' }
			<circle cx="12" cy="10" r="3" />
		</Svg>
	),
	map: (
		<Svg>
			<path d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z" />{ ' ' }
			<path d="M15 5.764v15" /> <path d="M9 3.236v15" />
		</Svg>
	),
	navigation: (
		<Svg>
			<polygon points="3 11 22 2 13 21 11 13 3 11" />
		</Svg>
	),
	compass: (
		<Svg>
			<circle cx="12" cy="12" r="10" />{ ' ' }
			<path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
		</Svg>
	),
	target: (
		<Svg>
			<circle cx="12" cy="12" r="10" /> <circle cx="12" cy="12" r="6" />{ ' ' }
			<circle cx="12" cy="12" r="2" />
		</Svg>
	),
	rocket: (
		<Svg>
			<path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />{ ' ' }
			<path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09" />{ ' ' }
			<path d="M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z" />{ ' ' }
			<path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05" />
		</Svg>
	),
	sparkles: (
		<Svg>
			<path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z" />{ ' ' }
			<path d="M20 2v4" /> <path d="M22 4h-4" />{ ' ' }
			<circle cx="4" cy="20" r="2" />
		</Svg>
	),
	hash: (
		<Svg>
			<line x1="4" x2="20" y1="9" y2="9" />{ ' ' }
			<line x1="4" x2="20" y1="15" y2="15" />{ ' ' }
			<line x1="10" x2="8" y1="3" y2="21" />{ ' ' }
			<line x1="16" x2="14" y1="3" y2="21" />
		</Svg>
	),
	key: (
		<Svg>
			<path d="m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4" />{ ' ' }
			<path d="m21 2-9.6 9.6" /> <circle cx="7.5" cy="15.5" r="5.5" />
		</Svg>
	),
	lightbulb: (
		<Svg>
			<path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />{ ' ' }
			<path d="M9 18h6" /> <path d="M10 22h4" />
		</Svg>
	),
	palette: (
		<Svg>
			<path d="M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z" />{ ' ' }
			<circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />{ ' ' }
			<circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />{ ' ' }
			<circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />{ ' ' }
			<circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
		</Svg>
	),
	coffee: (
		<Svg>
			<path d="M10 2v2" /> <path d="M14 2v2" />{ ' ' }
			<path d="M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1" />{ ' ' }
			<path d="M6 2v2" />
		</Svg>
	),
	monitor: (
		<Svg>
			<rect width="20" height="14" x="2" y="3" rx="2" />{ ' ' }
			<line x1="8" x2="16" y1="21" y2="21" />{ ' ' }
			<line x1="12" x2="12" y1="17" y2="21" />
		</Svg>
	),
	smartphone: (
		<Svg>
			<rect width="14" height="20" x="5" y="2" rx="2" ry="2" />{ ' ' }
			<path d="M12 18h.01" />
		</Svg>
	),
	laptop: (
		<Svg>
			<path d="M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z" />{ ' ' }
			<path d="M20.054 15.987H3.946" />
		</Svg>
	),
	server: (
		<Svg>
			<rect width="20" height="8" x="2" y="2" rx="2" ry="2" />{ ' ' }
			<rect width="20" height="8" x="2" y="14" rx="2" ry="2" />{ ' ' }
			<line x1="6" x2="6.01" y1="6" y2="6" />{ ' ' }
			<line x1="6" x2="6.01" y1="18" y2="18" />
		</Svg>
	),
	database: (
		<Svg>
			<ellipse cx="12" cy="5" rx="9" ry="3" />{ ' ' }
			<path d="M3 5V19A9 3 0 0 0 21 19V5" />{ ' ' }
			<path d="M3 12A9 3 0 0 0 21 12" />
		</Svg>
	),
	battery: (
		<Svg>
			<path d="M 22 14 L 22 10" />{ ' ' }
			<rect x="2" y="6" width="16" height="12" rx="2" />
		</Svg>
	),
	sun: (
		<Svg>
			<circle cx="12" cy="12" r="4" /> <path d="M12 2v2" />{ ' ' }
			<path d="M12 20v2" /> <path d="m4.93 4.93 1.41 1.41" />{ ' ' }
			<path d="m17.66 17.66 1.41 1.41" /> <path d="M2 12h2" />{ ' ' }
			<path d="M20 12h2" /> <path d="m6.34 17.66-1.41 1.41" />{ ' ' }
			<path d="m19.07 4.93-1.41 1.41" />
		</Svg>
	),
	moon: (
		<Svg>
			<path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" />
		</Svg>
	),
	sunrise: (
		<Svg>
			<path d="M12 2v8" /> <path d="m4.93 10.93 1.41 1.41" />{ ' ' }
			<path d="M2 18h2" /> <path d="M20 18h2" />{ ' ' }
			<path d="m19.07 10.93-1.41 1.41" /> <path d="M22 22H2" />{ ' ' }
			<path d="m8 6 4-4 4 4" /> <path d="M16 18a4 4 0 0 0-8 0" />
		</Svg>
	),
	cloud: (
		<Svg>
			<path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
		</Svg>
	),
	droplet: (
		<Svg>
			<path d="M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z" />
		</Svg>
	),
	flame: (
		<Svg>
			<path d="M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4" />
		</Svg>
	),
	leaf: (
		<Svg>
			<path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />{ ' ' }
			<path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
		</Svg>
	),
	wind: (
		<Svg>
			<path d="M12.8 19.6A2 2 0 1 0 14 16H2" />{ ' ' }
			<path d="M17.5 8a2.5 2.5 0 1 1 2 4H2" />{ ' ' }
			<path d="M9.8 4.4A2 2 0 1 1 11 8H2" />
		</Svg>
	),
};

/**
 * Picker metadata — label + search keywords + category, in display order.
 * `slug` always exists in ICON_LIBRARY (and Icons.php).
 */
export const ICON_META = [
	{
		slug: 'arrow-right',
		label: __( 'Arrow right', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'arrow right next forward',
	},
	{
		slug: 'arrow-left',
		label: __( 'Arrow left', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'arrow left back previous',
	},
	{
		slug: 'arrow-up',
		label: __( 'Arrow up', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'arrow up top',
	},
	{
		slug: 'arrow-down',
		label: __( 'Arrow down', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'arrow down bottom',
	},
	{
		slug: 'arrow-up-right',
		label: __( 'Arrow up-right', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'arrow diagonal external',
	},
	{
		slug: 'chevron-right',
		label: __( 'Chevron right', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'chevron right caret',
	},
	{
		slug: 'chevron-left',
		label: __( 'Chevron left', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'chevron left caret back',
	},
	{
		slug: 'chevron-up',
		label: __( 'Chevron up', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'chevron up caret collapse',
	},
	{
		slug: 'chevron-down',
		label: __( 'Chevron down', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'chevron down caret expand',
	},
	{
		slug: 'chevrons-right',
		label: __( 'Chevrons right', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'chevrons double right fast',
	},
	{
		slug: 'external-link',
		label: __( 'External link', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'external link out open',
	},
	{
		slug: 'move',
		label: __( 'Move', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'move drag arrows',
	},
	{
		slug: 'refresh-cw',
		label: __( 'Refresh', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'refresh reload sync rotate',
	},
	{
		slug: 'more-horizontal',
		label: __( 'More', 'axiom-blocks' ),
		category: 'arrows',
		keywords: 'more dots menu ellipsis',
	},
	{
		slug: 'check',
		label: __( 'Check', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'check tick done yes',
	},
	{
		slug: 'check-circle',
		label: __( 'Check circle', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'check circle success done',
	},
	{
		slug: 'x',
		label: __( 'Close', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'x close cancel cross',
	},
	{
		slug: 'circle-x',
		label: __( 'Close circle', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'x close cancel circle error',
	},
	{
		slug: 'plus',
		label: __( 'Plus', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'plus add new',
	},
	{
		slug: 'minus',
		label: __( 'Minus', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'minus remove subtract',
	},
	{
		slug: 'circle-plus',
		label: __( 'Plus circle', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'plus add circle new',
	},
	{
		slug: 'menu',
		label: __( 'Menu', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'menu hamburger lines',
	},
	{
		slug: 'list',
		label: __( 'List', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'list bullet items',
	},
	{
		slug: 'layout-grid',
		label: __( 'Grid', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'grid layout tiles',
	},
	{
		slug: 'search',
		label: __( 'Search', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'search find magnifier',
	},
	{
		slug: 'filter',
		label: __( 'Filter', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'filter funnel sort',
	},
	{
		slug: 'sliders-horizontal',
		label: __( 'Sliders', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'sliders controls adjust settings',
	},
	{
		slug: 'settings',
		label: __( 'Settings', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'settings gear cog options',
	},
	{
		slug: 'info',
		label: __( 'Info', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'info information about',
	},
	{
		slug: 'circle-help',
		label: __( 'Help', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'help question support faq',
	},
	{
		slug: 'alert-triangle',
		label: __( 'Alert', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'alert warning caution',
	},
	{
		slug: 'ban',
		label: __( 'Ban', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'ban block forbidden no',
	},
	{
		slug: 'eye',
		label: __( 'Eye', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'eye view visible preview',
	},
	{
		slug: 'eye-off',
		label: __( 'Eye off', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'eye off hide hidden',
	},
	{
		slug: 'lock',
		label: __( 'Lock', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'lock secure private',
	},
	{
		slug: 'shield',
		label: __( 'Shield', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'shield secure protect',
	},
	{
		slug: 'bookmark',
		label: __( 'Bookmark', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'bookmark save flag',
	},
	{
		slug: 'download',
		label: __( 'Download', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'download save export',
	},
	{
		slug: 'upload',
		label: __( 'Upload', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'upload import send',
	},
	{
		slug: 'power',
		label: __( 'Power', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'power on off toggle',
	},
	{
		slug: 'log-in',
		label: __( 'Log in', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'login signin enter',
	},
	{
		slug: 'log-out',
		label: __( 'Log out', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'logout signout exit',
	},
	{
		slug: 'zap',
		label: __( 'Zap', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'zap bolt lightning fast',
	},
	{
		slug: 'pencil',
		label: __( 'Edit', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'edit pencil write',
	},
	{
		slug: 'trash-2',
		label: __( 'Delete', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'trash delete remove bin',
	},
	{
		slug: 'copy',
		label: __( 'Copy', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'copy duplicate clone',
	},
	{
		slug: 'clipboard',
		label: __( 'Clipboard', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'clipboard paste copy',
	},
	{
		slug: 'scissors',
		label: __( 'Cut', 'axiom-blocks' ),
		category: 'ui',
		keywords: 'scissors cut trim',
	},
	{
		slug: 'file',
		label: __( 'File', 'axiom-blocks' ),
		category: 'files',
		keywords: 'file document blank',
	},
	{
		slug: 'file-text',
		label: __( 'Document', 'axiom-blocks' ),
		category: 'files',
		keywords: 'file text document page',
	},
	{
		slug: 'folder',
		label: __( 'Folder', 'axiom-blocks' ),
		category: 'files',
		keywords: 'folder directory',
	},
	{
		slug: 'folder-open',
		label: __( 'Folder open', 'axiom-blocks' ),
		category: 'files',
		keywords: 'folder open directory',
	},
	{
		slug: 'paperclip',
		label: __( 'Attachment', 'axiom-blocks' ),
		category: 'files',
		keywords: 'paperclip attach file',
	},
	{
		slug: 'printer',
		label: __( 'Print', 'axiom-blocks' ),
		category: 'files',
		keywords: 'printer print',
	},
	{
		slug: 'archive',
		label: __( 'Archive', 'axiom-blocks' ),
		category: 'files',
		keywords: 'archive box store',
	},
	{
		slug: 'cart',
		label: __( 'Cart', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'cart shopping buy',
	},
	{
		slug: 'shopping-bag',
		label: __( 'Shopping bag', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'bag shopping buy store',
	},
	{
		slug: 'store',
		label: __( 'Store', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'store shop market',
	},
	{
		slug: 'tag',
		label: __( 'Tag', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'tag price label sale',
	},
	{
		slug: 'gift',
		label: __( 'Gift', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'gift present reward',
	},
	{
		slug: 'credit-card',
		label: __( 'Credit card', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'card payment checkout pay',
	},
	{
		slug: 'wallet',
		label: __( 'Wallet', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'wallet money pay',
	},
	{
		slug: 'banknote',
		label: __( 'Banknote', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'banknote cash money bill',
	},
	{
		slug: 'dollar-sign',
		label: __( 'Dollar', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'dollar money price currency',
	},
	{
		slug: 'percent',
		label: __( 'Percent', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'percent discount sale off',
	},
	{
		slug: 'receipt',
		label: __( 'Receipt', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'receipt invoice bill order',
	},
	{
		slug: 'package',
		label: __( 'Package', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'package box parcel ship',
	},
	{
		slug: 'truck',
		label: __( 'Truck', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'truck delivery shipping',
	},
	{
		slug: 'ticket',
		label: __( 'Ticket', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'ticket coupon voucher',
	},
	{
		slug: 'award',
		label: __( 'Award', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'award badge prize quality',
	},
	{
		slug: 'trending-up',
		label: __( 'Trending up', 'axiom-blocks' ),
		category: 'commerce',
		keywords: 'trending up growth chart',
	},
	{
		slug: 'mail',
		label: __( 'Mail', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'mail email envelope',
	},
	{
		slug: 'at-sign',
		label: __( 'At sign', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'at email mention',
	},
	{
		slug: 'phone',
		label: __( 'Phone', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'phone call telephone',
	},
	{
		slug: 'send',
		label: __( 'Send', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'send submit paper plane',
	},
	{
		slug: 'message-circle',
		label: __( 'Message', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'message chat comment bubble',
	},
	{
		slug: 'message-square',
		label: __( 'Comment', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'comment chat message square',
	},
	{
		slug: 'inbox',
		label: __( 'Inbox', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'inbox messages mail',
	},
	{
		slug: 'bell',
		label: __( 'Bell', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'bell notification alert',
	},
	{
		slug: 'megaphone',
		label: __( 'Megaphone', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'megaphone announce promote',
	},
	{
		slug: 'globe',
		label: __( 'Globe', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'globe world web internet',
	},
	{
		slug: 'link',
		label: __( 'Link', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'link chain url',
	},
	{
		slug: 'share',
		label: __( 'Share', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'share social network',
	},
	{
		slug: 'rss',
		label: __( 'RSS', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'rss feed subscribe',
	},
	{
		slug: 'wifi',
		label: __( 'Wi-Fi', 'axiom-blocks' ),
		category: 'communication',
		keywords: 'wifi wireless network signal',
	},
	{
		slug: 'play',
		label: __( 'Play', 'axiom-blocks' ),
		category: 'media',
		keywords: 'play video start',
	},
	{
		slug: 'pause',
		label: __( 'Pause', 'axiom-blocks' ),
		category: 'media',
		keywords: 'pause stop',
	},
	{
		slug: 'skip-forward',
		label: __( 'Skip forward', 'axiom-blocks' ),
		category: 'media',
		keywords: 'skip forward next',
	},
	{
		slug: 'skip-back',
		label: __( 'Skip back', 'axiom-blocks' ),
		category: 'media',
		keywords: 'skip back previous',
	},
	{
		slug: 'image',
		label: __( 'Image', 'axiom-blocks' ),
		category: 'media',
		keywords: 'image picture photo',
	},
	{
		slug: 'video',
		label: __( 'Video', 'axiom-blocks' ),
		category: 'media',
		keywords: 'video film movie',
	},
	{
		slug: 'film',
		label: __( 'Film', 'axiom-blocks' ),
		category: 'media',
		keywords: 'film movie cinema reel',
	},
	{
		slug: 'music',
		label: __( 'Music', 'axiom-blocks' ),
		category: 'media',
		keywords: 'music note audio song',
	},
	{
		slug: 'headphones',
		label: __( 'Headphones', 'axiom-blocks' ),
		category: 'media',
		keywords: 'headphones audio listen',
	},
	{
		slug: 'mic',
		label: __( 'Microphone', 'axiom-blocks' ),
		category: 'media',
		keywords: 'mic microphone record voice',
	},
	{
		slug: 'volume-2',
		label: __( 'Volume', 'axiom-blocks' ),
		category: 'media',
		keywords: 'volume sound speaker audio',
	},
	{
		slug: 'camera',
		label: __( 'Camera', 'axiom-blocks' ),
		category: 'media',
		keywords: 'camera photo capture',
	},
	{
		slug: 'user',
		label: __( 'User', 'axiom-blocks' ),
		category: 'people',
		keywords: 'user person account profile',
	},
	{
		slug: 'users',
		label: __( 'Users', 'axiom-blocks' ),
		category: 'people',
		keywords: 'users people team group',
	},
	{
		slug: 'user-plus',
		label: __( 'Add user', 'axiom-blocks' ),
		category: 'people',
		keywords: 'user add person new',
	},
	{
		slug: 'smile',
		label: __( 'Smile', 'axiom-blocks' ),
		category: 'people',
		keywords: 'smile happy emoji face',
	},
	{
		slug: 'heart',
		label: __( 'Heart', 'axiom-blocks' ),
		category: 'people',
		keywords: 'heart like love favourite',
	},
	{
		slug: 'star',
		label: __( 'Star', 'axiom-blocks' ),
		category: 'people',
		keywords: 'star rating favourite',
	},
	{
		slug: 'thumbs-up',
		label: __( 'Thumbs up', 'axiom-blocks' ),
		category: 'people',
		keywords: 'thumbs up like approve',
	},
	{
		slug: 'thumbs-down',
		label: __( 'Thumbs down', 'axiom-blocks' ),
		category: 'people',
		keywords: 'thumbs down dislike',
	},
	{
		slug: 'trophy',
		label: __( 'Trophy', 'axiom-blocks' ),
		category: 'people',
		keywords: 'trophy win award winner',
	},
	{
		slug: 'flag',
		label: __( 'Flag', 'axiom-blocks' ),
		category: 'people',
		keywords: 'flag report mark',
	},
	{
		slug: 'home',
		label: __( 'Home', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'home house main',
	},
	{
		slug: 'calendar',
		label: __( 'Calendar', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'calendar date event schedule',
	},
	{
		slug: 'clock',
		label: __( 'Clock', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'clock time hour',
	},
	{
		slug: 'map-pin',
		label: __( 'Map pin', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'map pin location place',
	},
	{
		slug: 'map',
		label: __( 'Map', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'map location directions',
	},
	{
		slug: 'navigation',
		label: __( 'Navigation', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'navigation compass direction',
	},
	{
		slug: 'compass',
		label: __( 'Compass', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'compass direction explore',
	},
	{
		slug: 'target',
		label: __( 'Target', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'target goal aim focus',
	},
	{
		slug: 'rocket',
		label: __( 'Rocket', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'rocket launch startup fast',
	},
	{
		slug: 'sparkles',
		label: __( 'Sparkles', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'sparkles shine new magic',
	},
	{
		slug: 'hash',
		label: __( 'Hash', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'hash hashtag tag number',
	},
	{
		slug: 'key',
		label: __( 'Key', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'key password access unlock',
	},
	{
		slug: 'lightbulb',
		label: __( 'Idea', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'lightbulb idea tip',
	},
	{
		slug: 'palette',
		label: __( 'Palette', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'palette colour art design',
	},
	{
		slug: 'coffee',
		label: __( 'Coffee', 'axiom-blocks' ),
		category: 'misc',
		keywords: 'coffee cup cafe break',
	},
	{
		slug: 'monitor',
		label: __( 'Monitor', 'axiom-blocks' ),
		category: 'tech',
		keywords: 'monitor desktop screen computer',
	},
	{
		slug: 'smartphone',
		label: __( 'Smartphone', 'axiom-blocks' ),
		category: 'tech',
		keywords: 'smartphone mobile phone device',
	},
	{
		slug: 'laptop',
		label: __( 'Laptop', 'axiom-blocks' ),
		category: 'tech',
		keywords: 'laptop computer device',
	},
	{
		slug: 'server',
		label: __( 'Server', 'axiom-blocks' ),
		category: 'tech',
		keywords: 'server host database cloud',
	},
	{
		slug: 'database',
		label: __( 'Database', 'axiom-blocks' ),
		category: 'tech',
		keywords: 'database data storage',
	},
	{
		slug: 'battery',
		label: __( 'Battery', 'axiom-blocks' ),
		category: 'tech',
		keywords: 'battery power charge',
	},
	{
		slug: 'sun',
		label: __( 'Sun', 'axiom-blocks' ),
		category: 'nature',
		keywords: 'sun light day bright',
	},
	{
		slug: 'moon',
		label: __( 'Moon', 'axiom-blocks' ),
		category: 'nature',
		keywords: 'moon night dark',
	},
	{
		slug: 'sunrise',
		label: __( 'Sunrise', 'axiom-blocks' ),
		category: 'nature',
		keywords: 'sunrise dawn morning',
	},
	{
		slug: 'cloud',
		label: __( 'Cloud', 'axiom-blocks' ),
		category: 'nature',
		keywords: 'cloud weather sky',
	},
	{
		slug: 'droplet',
		label: __( 'Droplet', 'axiom-blocks' ),
		category: 'nature',
		keywords: 'droplet water drop liquid',
	},
	{
		slug: 'flame',
		label: __( 'Flame', 'axiom-blocks' ),
		category: 'nature',
		keywords: 'flame fire hot burn',
	},
	{
		slug: 'leaf',
		label: __( 'Leaf', 'axiom-blocks' ),
		category: 'nature',
		keywords: 'leaf nature eco plant',
	},
	{
		slug: 'wind',
		label: __( 'Wind', 'axiom-blocks' ),
		category: 'nature',
		keywords: 'wind air breeze weather',
	},
];

/** Flat slug list (render order / validation). */
export const ICON_SLUGS = ICON_META.map( ( i ) => i.slug );
